### PR TITLE
Added user settings

### PR DESCRIPTION
**Pull request by fivepointseven**
New user controller will allow settings and tons of other cool shit

---
This change is [Reviewable](https://reviewable.io/reviews/muzicn/testnewflow/5)

### CODE REVIEW

**Comment by muzicn** [comment]
Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[myapp/lib/controllers/userController.js, line 7 at r1](https://reviewable.io:443/reviews/muzicn/testnewflow/5#-KebQVxhCS3JyszpIZN7:-KebQVxhCS3JyszpIZN8:bdpnuy) ([raw file](https://github.com/muzicn/testnewflow/blob/b264dd8e820afce789147a0714fbe96b3fbac30a/myapp/lib/controllers/userController.js#L7)):*
> ```JavaScript
> 		userSettings = newSettings;
> 		
> 		if (cb) cb(null, userSettings); // @TODO Implement type check
> ```

No more TODO!!!!!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/muzicn/testnewflow/5)*

**Comment by muzicn** [comment]
Reviewed 1 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/muzicn/testnewflow/5)*

**Comment by fivepointseven** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[myapp/lib/controllers/userController.js, line 7 at r1](https://reviewable.io:443/reviews/muzicn/testnewflow/5#-KebQVxhCS3JyszpIZN7:-KebS5ctmA6ga3F3Tfpx:byahuc2) ([raw file](https://github.com/muzicn/testnewflow/blob/b264dd8e820afce789147a0714fbe96b3fbac30a/myapp/lib/controllers/userController.js#L7)):*
<details><summary><i>Previously, muzicn wrote…</i></summary><blockquote>

No more TODO!!!!!
</blockquote></details>

Okay, I'll remove it

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/muzicn/testnewflow/5)*

**Comment by muzicn** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/muzicn/testnewflow/5#-:-KebTvZGiJfxilV8QsyH:bnfp4nl)*

**Pull request merged**
